<?php
declare(strict_types=1);
// Uses the native adapter test double established by module_lifecycle.php.
$GLOBALS['egmTest']=['instances'=>[],'sent'=>[],'locks'=>[],'simulateExclusiveUART'=>true];
$passed=0;$check=static function(bool $ok,string $label)use(&$passed):void{if(!$ok)throw new RuntimeException($label);$passed++;};
$m=new EnOceanGatewayManager(101);$a=new ESP3TransportArbiter(200);$a->Create();$m->Create();
$props=&$GLOBALS['egmTest']['instances'][101]['properties'];$props['EnableReadActions']=true;
$GLOBALS['egmTest']['instances'][200]['properties']['EnableMaintenance']=true;
$GLOBALS['egmTest']['instances'][300]['properties']=['Port'=>'/dev/fixture','Open'=>true];$a->ApplyChanges();
$check(count($GLOBALS['egmTest']['sent'])===0,'Create/initial Apply never sends');
$check($props['BaseIDSource']==='saved'&&$props['ManualBaseID']==='','New instance has no automatic Master target');
$check(str_starts_with(json_decode($m->GetProductSnapshot(),true)['targetMessage'],'Noch keine Master-ID festgelegt.'),'B8.3 empty Master is normal user state, not codec error');
$check($m->SetMasterBaseID('FFC2F700','manual',true),'Explicit local Master created');
$check($props['BaseIDSource']==='saved'&&$props['ManualBaseID']==='','Saving Master does not apply hardware target');
$check(count($GLOBALS['egmTest']['sent'])===0,'Local Master has no hardware communication');
$read=static function(EnOceanGatewayManager $m,bool $target=false):void{
    if(!($target?$m->CheckMasterTransfer():$m->RefreshProductGateway()))throw new RuntimeException('Expected read-only start');
    (new ESP3TransportArbiter(200))->ReceiveData(json_encode(['DataID'=>'{018EF6B5-AB94-40C6-AA53-46943E824ACF}','Buffer'=>'55002100022600020B01000206030001020304454F0103474154455741594354524C00000000007F']));
    $m->ProcessProductWorkflow();
    (new ESP3TransportArbiter(200))->ReceiveData(json_encode(['DataID'=>'{018EF6B5-AB94-40C6-AA53-46943E824ACF}','Buffer'=>'5500050102DB00FFC2F780084B']));
    $m->ProcessProductWorkflow();
};
$read($m);$s=json_decode($m->GetProductSnapshot(),true);
$check($s['hardware']['baseID']==='FFC2F780'&&$s['gateway']['master']==='FFC2F700','Real adapter parser keeps hardware and Master independent');
$check($s['masterTargetSelection'][1]['value']==='FFC2F700'&&!$s['targetValidated'],'Fresh read exposes option, not applied target');
$check(str_starts_with($s['targetMessage'],'Noch kein Transferziel angewandt.'),'B8.3 unapplied native target has explicit instruction, not codec error');
$form=json_decode($m->GetConfigurationForm(),true);$option=$form['elements'][2]['items'][1]['options'][1]['value'];
// Emulate ONLY the documented native console's user choice + normal Apply.
$before=count($GLOBALS['egmTest']['sent']);foreach($option as$p)$props[$p['name']]=$p['value'];$m->ApplyChanges();
$check($props['ManualBaseID']==='FFC2F700'&&$props['BaseIDSource']==='manual','Conscious native MultiSelect applies both existing properties');
$check(count($GLOBALS['egmTest']['sent'])===$before,'Applying target emits no hardware/control packet');
$after=json_decode($m->GetProductSnapshot(),true);
$check(!$after['fresh']&&!$after['targetValidated'],'Apply invalidates proofs rather than reusing reads');
$check($after['gateway']['master']==='FFC2F700','Apply never replaces Master');
$read($m,true);$s=json_decode($m->GetProductSnapshot(),true);
$check($s['targetValidated']&&$s['appliedTarget']==='FFC2F700','Fresh post-Apply target validates through native adapter');
$check(($s['flow']['phase']??'')==='TARGET_VALIDATED','Read-only flow reaches target-validation state');
$check($s['flow']['target']==='FFC2F700'&&$s['flow']['review']['expectedCounter']===7,'Read-only review captures exact Master target and existing counter preview');
$check($s['hardware']['counter']===8&&$s['hardware']['baseID']==='FFC2F780','Target preparation changes neither chip Base-ID nor counter');
$check(json_decode($a->GetWriteTransactionView(),true)['state']==='IDLE','B8.2 creates no WriteTransaction');
$check(!file_exists(IPS_GetKernelDir().'/egm-write-journal-200/transactions.ndjson'),'B8.2 creates no WAL intent');
$check(count(array_filter($GLOBALS['egmTest']['sent'],fn($p)=>str_starts_with($p[1]['Operation']??'','B6_')))===0,'No B6_BEGIN/confirmation/control packets from target flow');
$check(!$m->ConfirmMasterTransfer(),'Direct confirmation cannot start B8.2 product transaction');
$check($m->SetMasterBaseID('FFC2F800','manual',true),'User may independently change local Master');
$before=count($GLOBALS['egmTest']['sent']);$check(!$m->CheckMasterTransfer(),'Changed Master rejects stale applied target before reads');
$check(count($GLOBALS['egmTest']['sent'])===$before,'Mismatched applied target has no hardware communication');
$GLOBALS['egmTest']['instances'][101]['active']=false;$m->MessageSink(1,300,IM_CHANGESTATUS,[104]);
$check($GLOBALS['egmTest']['instances'][101]['status']===201,'Disconnect still updates status');
$GLOBALS['egmTest']['instances'][101]['active']=true;$m->MessageSink(2,300,IM_CHANGESTATUS,[102]);
$check($GLOBALS['egmTest']['instances'][101]['status']===102,'Reconnect still updates status');
$check(count($GLOBALS['egmTest']['sent'])===$before,'Reconnect does not start read/write/control');
$audit=json_decode($a->GetTrafficAudit(),true);
$check(count($audit)===4&&count(array_filter($audit,fn($r)=>!in_array($r['frameHex'],['5500010005700309','5500010005700838'],true)))===0,'Only exact version/Base-ID reads reached mocked parent');
$check(json_decode($a->GetWriteTransactionView(),true)['hardwareWriteBarrier']&&!json_decode($a->GetWriteTransactionView(),true)['hardwareWriteEnabled'],'Actual adapter hardware barrier remains true');
$obs=json_decode($GLOBALS['egmTest']['instances'][101]['attributes']['ReadObservations'],true);foreach($obs as&$ob)$ob['readAt']=gmdate('c',time()-61);unset($ob);
$GLOBALS['egmTest']['instances'][101]['attributes']['ReadObservations']=json_encode($obs);
$GLOBALS['egmTest']['instances'][101]['buffers']['ProductFlow']=json_encode(['phase'=>'TARGET_VALIDATED','review'=>['target'=>'FFC2F700']]);
$before=count($GLOBALS['egmTest']['sent']);$m->ProcessProductWorkflow();
$check(json_decode($GLOBALS['egmTest']['instances'][101]['buffers']['ProductFlow'],true)['phase']==='TARGET_STALE','TTL stays 60 seconds; UI validation expires without automatic refresh');
$check(count($GLOBALS['egmTest']['sent'])===$before,'Expiry never creates reads, transactions or writes');
echo 'PASS: '.$passed.' B8.2 module/callback assertions'.PHP_EOL;
