<?php
declare(strict_types=1);
// Native callbacks are test doubles; never a real Symcon installation or UART.
$GLOBALS['egmTest']=['instances'=>[],'sent'=>[],'locks'=>[],'simulateExclusiveUART'=>true];
$passed=0;
$check=static function(bool $ok,string $label)use(&$passed):void{if(!$ok)throw new RuntimeException($label);$passed++;};
$m=new EnOceanGatewayManager(101);$a=new ESP3TransportArbiter(200);$a->Create();$m->Create();
$props=&$GLOBALS['egmTest']['instances'][101]['properties'];$props['EnableReadActions']=true;
$GLOBALS['egmTest']['instances'][200]['properties']['EnableMaintenance']=true;
$GLOBALS['egmTest']['instances'][300]['properties']=['Port'=>'/dev/fixture','Open'=>true];$a->ApplyChanges();
$snapshot=static fn():array=>json_decode((new EnOceanGatewayManager(101))->GetProductSnapshot(),true);
$reloads=static fn():int=>$GLOBALS['egmTest']['instances'][101]['reloads']??0;
$check($m->SetMasterBaseID('FFC2F700','manual',true),'First local Master save');
$before=$reloads();
$check($m->SetMasterBaseID('FFC2F800','manual',true),'Second local Master save');
$check($reloads()>$before,'UAT: repeated local Master save must immediately refresh the form');
$check($snapshot()['gateway']['master']==='FFC2F800','Updated Master visible without hardware read');
$check(count($GLOBALS['egmTest']['sent'])===0,'Local Master save sends no hardware packets');
$deliver=static function(string $hex)use($a):void{$a->ReceiveData(json_encode(['DataID'=>'{018EF6B5-AB94-40C6-AA53-46943E824ACF}','Buffer'=>$hex]));};
$version='55002100022600020B01000206030001020304454F0103474154455741594354524C00000000007F';
$base='5500050102DB00FFC2F780084B';
$complete=static function()use($m,$deliver,$version,$base):void{$deliver($version);$m->ProcessProductWorkflow();$deliver($base);$m->ProcessProductWorkflow();};
$check($m->RefreshProductGateway(),'Bound gateway refresh begins');$complete();
$s=$snapshot();
$check($s['fresh']&&$s['hardware']['baseID']==='FFC2F780','Fresh complete gateway read');
$check($s['displayHardware']['baseID']==='FFC2F780'&&!$s['displayHistorical'],'Fresh display derived from hardware');
$check($s['gateway']['acceptedEURID']==='01020304','First proven physical identity anchored locally');
$before=count($GLOBALS['egmTest']['sent']);$beforeReload=$reloads();
$check($m->SetMasterBaseID('','hardware',true),'Current hardware as local Master');
$check($reloads()>$beforeReload&&$snapshot()['gateway']['master']==='FFC2F780','Hardware Master immediately displayed');
$beforeReload=$reloads();$check($m->SetMasterBaseID('FFC2F700','manual',true),'Manually change Master');
$check($reloads()>$beforeReload&&$snapshot()['gateway']['master']==='FFC2F700','Manual Master immediately displayed');
$check(count($GLOBALS['egmTest']['sent'])===$before,'Both local saves require no fresh hardware communication');
$form=json_decode($m->GetConfigurationForm(),true);
$buttons=static function(array $form):array{$out=[];$walk=static function(array $items)use(&$walk,&$out):void{foreach($items as$x){if(!is_array($x))continue;if(($x['type']??'')==='Button')$out[]=$x;foreach($x as$v)if(is_array($v))$walk($v);}};$walk([$form]);return $out;};
$all=json_encode($form,JSON_UNESCAPED_UNICODE);
foreach(['EGMM_BeginWriteTransaction(','EGMM_AuthorizeWriteTransaction(','EGMM_ConfirmWriteTransaction(']as$developerAction)
    $check(!str_contains($all,$developerAction),'Developer transaction controls absent from product UI '.$developerAction);
$check(!str_contains($all,'Später festlegen'),'No defer option with an existing Master');
$check(!str_contains($all,'Gateway automatisch suchen'),'No serial auto-discovery in manager UI');
$check(!str_contains($all,'Gateway manuell einrichten'),'Native gateway change is primary configuration path');
$primary=json_encode(array_filter($form['actions'],fn($x)=>($x['type']??'')!=='ExpansionPanel'),JSON_UNESCAPED_UNICODE);
foreach(['EURID','Transferziel','Arbiter','B5','B6','Angewandtes Ziel']as$jargon)$check(!str_contains($primary,$jargon),'No primary jargon '.$jargon);
$diagnostic=array_values(array_filter($form['actions'],fn($x)=>($x['caption']??'')==='Erweiterte Diagnose'))[0];
$check($diagnostic['expanded']===false,'Diagnostics closed by default');
$check($m->PrepareMasterChange(),'Simple action automatically starts safe read-only preflight');
$s=$snapshot();
$check(!$s['fresh']&&$s['hardware']['baseID']===null,'In-flight read invalidates safety proof');
$check($s['displayHardware']['baseID']==='FFC2F780'&&$s['displayHistorical'],'UAT: pending read retains explicitly historical gateway display');
$check(str_contains($m->GetConfigurationForm(),'GATEWAYCTRL'),'Known gateway remains visible while read-only check runs');
$complete();$s=$snapshot();
$check($s['flow']['phase']==='NEEDS_CONFIGURATION','Missing native binding asks for conscious configuration');
$check($props['BaseIDSource']==='saved'&&$props['ManualBaseID']==='','No automatic owner property mutation');
$check($s['hardware']['baseID']==='FFC2F780','Read-only preparation does not lose gateway');
$form=json_decode($m->GetConfigurationForm(),true);$choice=$form['elements'][2]['items'][1]['options'][1]['value'];
$check($form['elements'][2]['visible']&&$choice[1]['value']==='FFC2F700','Clear native Base-ID selection offered when needed');
foreach($choice as$p)$props[$p['name']]=$p['value'];$before=count($GLOBALS['egmTest']['sent']);$m->ApplyChanges();
$s=$snapshot();
$check($s['gateway']['master']==='FFC2F700','Master persists ApplyChanges');
$check(!$s['fresh']&&$s['hardware']['baseID']===null,'ApplyChanges does not preserve safety proof');
$check($s['displayHardware']['baseID']==='FFC2F780'&&$s['displayHistorical'],'ApplyChanges retains historical display only');
$check(count($GLOBALS['egmTest']['sent'])===$before,'ApplyChanges only schedules, never sends synchronously');
$check($m->PrepareMasterChange(),'Applied native Master can be checked without exposing internal phases');$complete();
$s=$snapshot();
$check($s['flow']['phase']==='TARGET_VALIDATED'&&$s['targetValidated'],'Existing native safety gates validate fresh target');
$check($s['flow']['review']['counter']===8&&$s['flow']['review']['expectedCounter']===7,'Hardware counter preview 8 to 7');
$check(json_decode($a->GetWriteTransactionView(),true)['state']==='IDLE','Simple preflight creates no WriteTransaction');
$check(!file_exists(IPS_GetKernelDir().'/egm-write-journal-200/transactions.ndjson'),'No hardware WAL intent');
$check(!$m->ConfirmMasterTransfer(),'Direct confirmation still blocked by immutable barrier');
$writeButtons=array_values(array_filter($buttons(json_decode($m->GetConfigurationForm(),true)),fn($x)=>($x['caption']??'')==='Base-ID jetzt ändern'));
$check(count($writeButtons)===1&&!$writeButtons[0]['enabled'],'Hardware write button disabled');
$m->CancelProductWorkflow();$check(($snapshot()['flow']??[])===[],'Cancellation clears UI flow');
$before=count($GLOBALS['egmTest']['sent']);$m->ProcessProductWorkflow();
$check(count($GLOBALS['egmTest']['sent'])===$before,'Cancellation triggers no delayed automatic read/write');
$obs=json_decode($GLOBALS['egmTest']['instances'][101]['attributes']['ReadObservations'],true);
foreach($obs as&$o)$o['readAt']=gmdate('c',time()-61);unset($o);
$GLOBALS['egmTest']['instances'][101]['attributes']['ReadObservations']=json_encode($obs);
$s=$snapshot();
$check(!$s['fresh']&&$s['displayHistorical']&&$s['hardware']['baseID']===null,'TTL remains 60s; historical cache does not satisfy freshness');
$before=count($GLOBALS['egmTest']['sent']);$check(!$m->SetMasterBaseID('','hardware',true),'Expired display cannot be saved as fresh hardware Master');
$check(count($GLOBALS['egmTest']['sent'])===$before,'Rejected stale save does not send');
$m->ApplyChanges();$before=count($GLOBALS['egmTest']['sent']);$m->ProcessProductWorkflow();
$check(count($GLOBALS['egmTest']['sent'])===$before+2,'One deferred initial read traverses manager and arbiter');$complete();
$m->ProcessProductWorkflow();$after=count($GLOBALS['egmTest']['sent']);$m->ProcessProductWorkflow();
$check(count($GLOBALS['egmTest']['sent'])===$after,'Successful initial read not repeatedly retried');
$logical=$snapshot()['gateway']['logicalID'];
$GLOBALS['egmTest']['instances'][101]['buffers']=[];(new EnOceanGatewayManager(101))->Create();
$check($snapshot()['gateway']['logicalID']===$logical&&$snapshot()['gateway']['master']==='FFC2F700','New callback object and cleared buffers preserve durable Master/identity');
$before=count($GLOBALS['egmTest']['sent']);$GLOBALS['egmTest']['instances'][101]['active']=false;$m->MessageSink(1,300,IM_CHANGESTATUS,[104]);
$check(!$snapshot()['connected'],'Disconnect reflected in presentation');
$GLOBALS['egmTest']['instances'][101]['active']=true;$m->MessageSink(2,300,IM_CHANGESTATUS,[102]);
$check($snapshot()['connected']&&count($GLOBALS['egmTest']['sent'])===$before,'Reconnect observer does not directly send');
$m->CancelProductWorkflow();
$GLOBALS['egmTest']['instances'][300]['properties']['Port']='/dev/different-fixture';
$s=$snapshot();$check(($s['displayHardware']['baseID']??null)===null,'Different endpoint cannot borrow display cache');
$GLOBALS['egmTest']['instances'][300]['properties']['Port']='/dev/fixture';
// Binding changes require an observed disconnect/reconnect even in the test double.
$GLOBALS['egmTest']['instances'][200]['active']=false;
(new ESP3TransportArbiter(200))->ApplyChanges();EGMA_GetReadSafetyContext(200);
$GLOBALS['egmTest']['instances'][200]['active']=true;
(new ESP3TransportArbiter(200))->ApplyChanges();$m->ApplyChanges();
$check($m->SetMasterBaseID('FFC2F780','manual',true),'Matching Master stored locally');
$check($m->RefreshProductGateway(),'Read matching gateway after observed reconnect');$complete();
$check(!$m->PrepareMasterChange(),'Matching IDs do not begin a needless change');
$form=json_decode($m->GetConfigurationForm(),true);
$primaryChange=array_values(array_filter($form['actions'],fn($x)=>str_starts_with($x['caption']??'','Base-ID des Gateways auf ')))[0];
$check(!$primaryChange['visible'],'Matching IDs hide primary hardware change action');
$p=\EnOceanGatewayManager\Product\GatewayTransportProfile::describe('network','ESP3');
$check(!$p['adapterAvailable']&&$p['capabilitiesMustBeRead'],'LAN model name never implies usable transport or commands');
$check(!\EnOceanGatewayManager\Product\GatewayTransportProfile::describe('serial','ESP2')['adapterAvailable'],'ESP2 cannot reuse ESP3 adapter');
$check(\EnOceanGatewayManager\Product\GatewayTransportProfile::describe('serial','ESP3')['adapterAvailable'],'Serial ESP3 descriptor available');
$reply=static function(string $data):string{$h=pack('nCC',strlen($data),0,2);return strtoupper(bin2hex(chr(85).$h.chr(\EnOceanGatewayManager\Protocol\ESP3Codec::crc8($h)).$data.chr(\EnOceanGatewayManager\Protocol\ESP3Codec::crc8($data))));};
$m->ApplyChanges();$m->ProcessProductWorkflow();$deliver($reply(chr(2)));$m->ProcessProductWorkflow();
$s=$snapshot();
$check(!$s['fresh']&&$s['displayHistorical']&&$s['displayHardware']['baseID']==='FFC2F780','RET_NOT_SUPPORTED retains historical display, not proof');
$before=count($GLOBALS['egmTest']['sent']);$m->ProcessProductWorkflow();$m->ProcessProductWorkflow();
$check(count($GLOBALS['egmTest']['sent'])===$before,'Failed initial read has no automatic retry or fallback');
$check(!$m->ConfirmMasterTransfer(),'Unsupported read cannot make confirmation writable');
$check($m->RefreshProductGateway(),'Explicit user may request a new read');
$different=hex2bin(str_replace('01020304','11223344',$version));
$different=substr($different,0,-1).chr(\EnOceanGatewayManager\Protocol\ESP3Codec::crc8(substr($different,6,-1)));
$deliver(strtoupper(bin2hex($different)));$m->ProcessProductWorkflow();$deliver($base);$m->ProcessProductWorkflow();
$s=$snapshot();
$check($s['replacement']&&$s['gateway']['acceptedEURID']==='01020304','Changed physical identity never silently reassigned');
$check($s['gateway']['master']==='FFC2F780','Gateway replacement preserves Master');
$before=count($GLOBALS['egmTest']['sent']);$check(!$m->PrepareMasterChange(),'Replacement blocks primary preparation until consciously assigned');
$check(count($GLOBALS['egmTest']['sent'])===$before,'Replacement rejection sends no packet');
$check($m->AcceptReplacement(),'Explicit replacement assignment local only');
$check($snapshot()['gateway']['acceptedEURID']==='11223344'&&$snapshot()['gateway']['master']==='FFC2F780','Explicit assignment changes identity, not Master');
$check(count($GLOBALS['egmTest']['sent'])===$before,'Assignment requires no hardware write');
$audit=json_decode($a->GetTrafficAudit(),true);
$check(count(array_filter($audit,fn($r)=>!in_array($r['frameHex'],['5500010005700309','5500010005700838'],true)))===0,'Only documented VERSION and IDBASE frames sent to mocked parent');
$check(json_decode($a->GetWriteTransactionView(),true)['hardwareWriteBarrier'],'Compiled hardware barrier unchanged');
// First-time setup, independently of the earlier manual-Master fixture.
$GLOBALS['egmTest']=['instances'=>[],'sent'=>[],'locks'=>[],'simulateExclusiveUART'=>true];
$a->Create();$m->Create();
$GLOBALS['egmTest']['instances'][101]['properties']['EnableReadActions']=true;
$GLOBALS['egmTest']['instances'][200]['properties']['EnableMaintenance']=true;
$GLOBALS['egmTest']['instances'][300]['properties']=['Port'=>'/dev/fixture','Open'=>true];$a->ApplyChanges();
$check(str_contains(json_encode(json_decode($m->GetConfigurationForm(),true),JSON_UNESCAPED_UNICODE),'Später festlegen'),'First setup offers defer without setting a Master');
$check($m->RefreshProductGateway(),'Initial hardware identity read');$complete();
$before=count($GLOBALS['egmTest']['sent']);$beforeReload=$reloads();
$check($m->SetMasterBaseID('','hardware',true),'First Master can be current hardware Base-ID');
$check($reloads()>$beforeReload&&$snapshot()['gateway']['master']==='FFC2F780','First hardware Master save immediately reloads and displays');
$check(count($GLOBALS['egmTest']['sent'])===$before,'First Master save is strictly local');
$check(!str_contains(json_encode(json_decode($m->GetConfigurationForm(),true),JSON_UNESCAPED_UNICODE),'Später festlegen'),'Defer disappears immediately after first save');
echo 'PASS: '.$passed.' UAT product assertions'.PHP_EOL;
